### ISSUE TITLE
Import von Reifendaten schlägt fehl

### ISSUE THREAD

**Issue by niklaskks** [axsemantics/axsemantics-python#4]
Beim importieren der Reifendaten springt mir der Importer regelmäßig raus.
Die Daten die es ins System schaffen sehen soweit gut aus.

Daten und Mappings sind angehängt:

Meldungen für vorhandene Datensätze werden korrekt ausgegeben:
Method: POST
Resource: https://api.ax-semantics.com/v1/content-project/4654/thing/
Payload: {"uid": 5539440, "pure_data": {"rim_diameter": 13.0, "vehicle_type": "car", "rim_protection": null, "wet_grip": "C", "exterior_noise": 70.0, "oem": null, "fuel_efficiency": "E", "speed_rating": "T", "aspect_ratio": 65.0, "width": "175", "runflat": null, "tire_type": "summer", "uid": 5539440, "load_index": "80", "Merkmalswert": null, "name": "BRILLANTIS 2", "manufacturer": "Barum"}, "content_project": 4654, "name": "BRILLANTIS 2"}
Response: 405 b'{"object":226742,"error":"Object with uid \'5539440\' already exists in this content project. Please use PUT to update this object: \'226742\'"}'

Die Fehlermeldung mit der es rausfliegt sieht so aus:
```
Traceback (most recent call last):
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 376, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 378, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1174, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 282, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 243, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 924, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 786, in read
    return self._sslobj.read(len, buffer)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 570, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 609, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 247, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/requests/packages/urllib3/packages/six.py", line 310, in reraise
    raise value
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 380, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 308, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.ax-semantics.com', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/axsemantics/net.py", line 50, in request_and_raise
    result = requests.post(url, headers=headers, json=params, timeout=5)
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/requests/api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/requests/adapters.py", line 449, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.ax-semantics.com', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/axsemantics/net.py", line 39, in request
    result = self.request_and_raise(method, url, headers, params)
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/axsemantics/net.py", line 60, in request_and_raise
    raise APIConnectionError
axsemantics.errors.APIConnectionError: <no further information

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 376, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 378, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1174, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 282, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 243, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 924, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 786, in read
    return self._sslobj.read(len, buffer)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 570, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 609, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 247, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/requests/packages/urllib3/packages/six.py", line 310, in reraise
    raise value
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 380, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 308, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.ax-semantics.com', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/axsemantics/net.py", line 50, in request_and_raise
    result = requests.post(url, headers=headers, json=params, timeout=5)
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/requests/api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/requests/adapters.py", line 449, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.ax-semantics.com', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/admin/Desktop/import/axsemantics-python-master/bin/excel_upload2.py", line 161, in <module>
    thing.create()
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/axsemantics/mixins.py", line 10, in create
    self.load_data(self.request('post', self.instance_url(), params=params))
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/axsemantics/base.py", line 64, in request
    response = requestor.request(method, url, params, headers)
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/axsemantics/net.py", line 44, in request
    result = self.request_and_raise(method, url, headers, params)
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/axsemantics/net.py", line 60, in request_and_raise
    raise APIConnectionError
axsemantics.errors.APIConnectionError: <no further information
```

**Comment by rixx** [comment]
Sieht von den Fehlermeldungen her nach einem Verbindungsfehler aus. Tritt der Fehler immer noch auf?
