### ISSUE TITLE
Errors resulting from Excell Import

### ISSUE THREAD

**Issue by niklaskks** [axsemantics/axsemantics-python#6]
Hi Team, my import failed with the following response:

Traceback (most recent call last):
  File "/Users/admin/Desktop/import/axsemantics-python-master/bin/excel_upload3.py", line 142, in <module>
    thing.create()
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/axsemantics/mixins.py", line 10, in create
    self.load_data(self.request('post', self.instance_url(), params=params))
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/axsemantics/base.py", line 64, in request
    response = requestor.request(method, url, params, headers)
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/axsemantics/net.py", line 39, in request
    result = self.request_and_raise(method, url, headers, params)
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/axsemantics/net.py", line 50, in request_and_raise
    result = requests.post(url, headers=headers, json=params, timeout=5)
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/requests/api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/requests/sessions.py", line 454, in request
    prep = self.prepare_request(req)
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/requests/sessions.py", line 388, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/requests/models.py", line 296, in prepare
    self.prepare_body(data, files, json)
  File "/Users/admin/Desktop/import/ax-semantics/lib/python3.5/site-packages/requests/models.py", line 422, in prepare_body
    body = complexjson.dumps(json)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 180, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: Timestamp('2003-01-01 00:00:00') is not JSON serializable

It would be great if you could give me some information regarding the cause of this failure.

Best regards
Niklas

**Comment by robert-weissgraeber** [comment]
It's a type error for the extraction of the timestamp field from excel. If you just use string type for this field it should work.
