### ISSUE TITLE
Rincewind Login Fail

### ISSUE THREAD

**Issue by rixx** [axsemantics/axsemantics-python#7]
```
$ python3 excel_upload.py Import_Kosmetik_KW27.xlsx
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/axsemantics/net.py", line 75, in request_and_raise
    result.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://training-api.ax-semantics.com/get-auth-token/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "excel_upload.py", line 153, in <module>
    axsemantics.login(AXSEMANTICS_USER, AXSEMANTICS_PASSWORD)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/axsemantics/utils.py", line 17, in login
    login_rincewind(user, password)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/axsemantics/utils.py", line 70, in login_rincewind
    params=data,
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/axsemantics/net.py", line 52, in request
    result = self.request_and_raise(method, url, headers, params, False)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/axsemantics/net.py", line 85, in request_and_raise
    raise APIError(result)
axsemantics.errors.APIError: <no further information>
```

This is an error happening whily trying to use the excel-upload script. Since this script doesn't even utilize rincewind functionality/information in any way, crashing because of failing rincewind authentication really, really, really should not happen.

**Comment by Gentle** [comment]
das ist ein failover, wenn myax sagt 401 dann rincewind fragen, wenn rincewind auch sagt 401 dann Login Error raisen, wenn mindestens einer von beiden sagt "das Passwort stimmt" weitermachen

**Comment by Gentle** [comment]
excel_upload sollte am besten login_myax benutzen

**Comment by rixx** [comment]
Würde erwarten, dass wenn da valide Authentifizierungsdaten für die myax angegeben werden, ein login(user, password) durchläuft und nicht einen Fehler schmeißt, aber ok, dann halt `login_myax`.

Wär cool, wenn du in Zukunft gucken würdest, dass das mitgelieferte Skript mit der Bibliothek zusammen funktionert.
